package Calculator;


/**
* Calculator/CalculatorInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* œroda, 3 marca 2021 15:45:00 CET
*/

public interface CalculatorInterface extends CalculatorInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalculatorInterface
