package Calculator;


/**
* Calculator/CalculatorInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* œroda, 3 marca 2021 15:45:00 CET
*/

public interface CalculatorInterfaceOperations 
{
  String run (String op, double a, double b, double c, double d);
  void shutdown ();
} // interface CalculatorInterfaceOperations
