package Calculator;


/**
* Calculator/CalculatorInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* œroda, 3 marca 2021 15:45:00 CET
*/

public abstract class CalculatorInterfacePOA extends org.omg.PortableServer.Servant
 implements Calculator.CalculatorInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("run", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculator/CalculatorInterface/run
       {
         String op = in.read_string ();
         double a = in.read_double ();
         double b = in.read_double ();
         double c = in.read_double ();
         double d = in.read_double ();
         String $result = null;
         $result = this.run (op, a, b, c, d);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Calculator/CalculatorInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculator/CalculatorInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CalculatorInterface _this() 
  {
    return CalculatorInterfaceHelper.narrow(
    super._this_object());
  }

  public CalculatorInterface _this(org.omg.CORBA.ORB orb) 
  {
    return CalculatorInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class CalculatorInterfacePOA
